[colors.primary]
background = "#1F2734"
foreground = "#839496"

[font]
size = 9.0

[font.normal]
family = "RobotoMono Nerd Font"

[[keyboard.bindings]]
action = "Up"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "Semicolon"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
