alias gs="git status"
alias gp="git push"
alias gpff="git pull --ff-only --prune"
alias gl="git log --max-count=8 --decorate --graph --color --pretty=format:'%C(yellow)%h %C(cyan)%ad%Cgreen%d %Creset%s %C(yellow)%an' --date=short"
alias gcm="git commit -m "
alias gd="git diff"
alias ga="git add ."
alias gc="git checkout "