#!/bin/zsh

function samabr() {
    [ -f Cargo.toml ] && {
        TORUN=${1:-RUST_BACKTRACE=1 cargo build && (cd .. && sam sync --stack-name rust-htmx --beta-features)}
        # TODO migrate to modd
        reflex -r '\.rs$' -s -- sh -c "$TORUN 2>&1"

#       RUST_BACKTRACE=1 cargo-watch -q -c -w src/ -x check
#       return
    }

    echo "Ecosystem not supported"
}
