[language.javascript]
command = "flow"
args = ["lsp"]
install = [["npm", "install", "-g", "flow-bin"]]

[language.typescript]
command = "typescript-language-server"
args = ["--stdio"]
install = [["npm", "install", "-g", "typescript-language-server"]]

[language.go]
command = "gopls"
args = ["serve"]
install = [["go", "get", "-u", "golang.org/x/tools/cmd/gopls"]]
