#!/bin/zsh

function ago() {
    [ -f go.mod ] || [ -f go.work ] && {
        TORUN=${1:-go run -tags=debug .}
        # TODO migrate to modd
        reflex -r '\.go$' -s -- sh -c "$TORUN 2>&1"
        return
    }

    [ -f Cargo.toml ] && {
      if [[ -z "${@// }" ]];then
        # disabled -x check
        RUST_BACKTRACE="${RUST_BACKTRACE:-0}" cargo-watch -c -w . -x "run --timings"
      else 
        RUNCMD="run --timings $@"
        # disabled -x check
        RUST_BACKTRACE="${RUST_BACKTRACE:-0}" cargo-watch -c -w . -x "$RUNCMD"
        return
      fi
    }

    [ -f pnpm-lock.yaml ] && {
        pnpm run dev --host
        return
    }

    [ -d .chalice ] && {
      # TODO migrate to modd
      reflex -r '\.py$' -s -- sh -c "chalice local"
      return
    }

    echo "Ecosystem not supported"
}
