#!/bin/zsh

function ato() {
    [ -f go.mod ] || [ -f go.work ] && {
        gotestsum --watch ./...
    }

    [ -f Cargo.toml ] && {
        RUNCMD="test -q $@"
        cargo watch -x check -x "$RUNCMD"
    }

    [ -f pnpm-lock.yaml ] && {
        pnpm run test
    }

    echo "Ecosystem not supported"
}
