#!/bin/zsh

function ato() {
    [ -f go.mod ] || [ -f go.work ] && {
        gotestsum --watch ./...
    }

    [ -f Cargo.toml ] && {
        RUNCMD="nextest run --timings $@"
        cargo-watch -c -w . -x "$RUNCMD"
    }

    [ -f pnpm-lock.yaml ] && {
        pnpm run test
    }

    echo "Ecosystem not supported"
}
