#!/bin/zsh

function ato() {
    [ -f go.mod ] && {
        gotestsum --watch .
    }

    [ -f Cargo.toml ] && {
        cargo watch -x check -x test
    }

    [ -f pnpm-lock.yaml ] && {
        pnpm run test
    }

    echo "Ecosystem not supported"
}
