#!/bin/zsh
# the file should only contain the function (no variables, no main code),
# to auto start the autoloaded function on first execution

togglexdpi() {
    SYMLINKFILE=${HOME}/.config/X11/.Xresources

    CURTARGET=$(readlink ${SYMLINKFILE})

    rm -f ${SYMLINKFILE}
    # # defaults to lodpi if .Xresources file does not exist
    if [[ $CURTARGET =~ "hidpi" ]]; then
        ln -s $DOTFILES/x/.Xresources.lodpi ${SYMLINKFILE}
        if [ $? -ne 0 ]; then return $?; fi
        type notify-send 1>/dev/null && notify-send -i display "lodpi mode" -u low
    else
        ln -s $DOTFILES/x/.Xresources.hidpi ${SYMLINKFILE}
        if [ $? -ne 0 ]; then return $?; fi
        # --mode 3840x2400
        xrandr --output Virtual-1 --auto --pos 0x0 --rotate normal --dpi 227 --scale 1x1
        type notify-send 1>/dev/null && notify-send -i display "hidpi mode" -u low
    fi
    . $DOTFILES/alacritty/zprofile.zsh
    . $DOTFILES/x/init.zsh
    i3-msg restart
}
