#!/usr/bin/zsh
PARENTDIR="$(dirname ${0:a:h})"

togglexdpi() {
  echo "togglexdpi PARENT $PARENTDIR"
  SYMLINKFILE=${HOME}/.config/X11/.Xresources
  PREFFILE=$XDG_CONFIG_HOME/X11/.Xresources-dpi-preference

  CURTARGET=$(readlink ${SYMLINKFILE})

  rm -f ${SYMLINKFILE}
  # # defaults to lodpi if .Xresources file does not exist
  if [[ $CURTARGET =~ "hidpi" ]]; then
    ln -s $PARENTDIR/.Xresources.lodpi ${SYMLINKFILE} 
    echo lodpi > $PREFFILE
    if [ $? -ne 0 ]; then return $?; fi
    xrandr --output Virtual-1 --auto --mode 5120x1440 --pos 0x0 --rotate normal --dpi 110 --scale 1x1
    if type notify-send 1>/dev/null; then
      notify-send -i display "lodpi activated"
    else 
      echo lodpi activated
    fi 
  else
    ln -s $PARENTDIR/.Xresources.hidpi ${SYMLINKFILE} 
    echo hidpi > $PREFFILE
    if [ $? -ne 0 ]; then return $?; fi
    # --mode 3840x2400
    xrandr --output Virtual-1 --auto --pos 0x0 --rotate normal --dpi 227 --scale 1x1
    if type notify-send 1>/dev/null; then
      notify-send -i display "hidpi activated"
    else 
      echo hidpi activated
    fi 
  fi
  . $DOTFILES/alacritty/zprofile.zsh
  . $DOTFILES/x/init.zsh
  i3-msg restart
}
